POSE2IMAGE:
  PATH:
    img_base : "/{dataset root}/img"    ##TODO
    kp_base : "/{dataset root}/keypoints"   ##TODO
    img_extension: '.jpg'


  TRAIN:
    CROP:
      W_bias: 500
      H_bias: 40
  HYPERPARAM:
    img_H : 640
    img_W : 640
    kp_var_root: [10,10,10,10,10,10,10,4,2,3,2,4,4]
    mask_sigma_perp: [35, 25, 25, 20, 25, 20, 10, 10]
    scale : 1.0
 

  INFER:
    root_node: [[822.07040391],[357.76986784]]
    ckpt_path: "{your root}/ckpt_final.pth"  ##TODO
    src_img_path: "{your root}/oliver_source/Auto_Lending_-_Last_Week_Tonight_with_John_Oliver_HBO-4U2eDJnwz_s_58_000_0_00_05.405405.jpg"   ##TODO
    src_kp_path: "{your root}/oliver_source/keypoints/Auto_Lending_-_Last_Week_Tonight_with_John_Oliver_HBO-4U2eDJnwz_s_58_000_0_00_05.405405.npy"  ##TODO


  
