POSE2IMAGE:
  PATH:
    img_base : "data/xiang/imgs"    
    kp_base : "data/xiang/keypoints"   
    img_extension: '.jpg'


  TRAIN:
    CROP:
      W_bias: 180
      H_bias: 40
  HYPERPARAM:
    img_H : 320
    img_W : 320
    kp_var_root: [10,10,8,10,10,10,10,4,2,3,2,4,4]
    mask_sigma_perp: [35, 25, 25, 20, 25, 18, 10, 12]
    scale : 1.0
 

  INFER:
    root_node: [[344.82444244],[222.39235733]]
    ckpt_path: "/mllab/codehub/Pose2Img/ckpt/xiang/ckpt_11.pth"  
    src_img_path: "data/xiang/imgs/xiang_007329.jpg"   
    src_kp_path: "data/xiang/keypoints/xiang_007329.npy"
    scale: 2.5720
