POSE2IMAGE:
  PATH:
    img_base : "/mllab/codehub/SpeechDrivesTemplates/datasets/speakers/xiang/frames/xiang"    
    kp_base : "/mllab/codehub/SpeechDrivesTemplates/datasets/speakers/xiang/tmp/cleaned_pose_2d/xiang"   
    img_extension: '.jpg'


  TRAIN:
    CROP:
      W_bias: 180
      H_bias: 40
  HYPERPARAM:
    img_H : 320
    img_W : 320
    kp_var_root: [10,10,10,10,10,10,10,4,2,3,2,4,4]
    mask_sigma_perp: [35, 25, 25, 20, 25, 20, 10, 10]
    scale : 1.0
 

  INFER:
    root_node: [[343.98968094],[222.96735321]]
    ckpt_path: "ckpt/xiang/ckpt_last.pth"  
    src_img_path: "/mllab/codehub/SpeechDrivesTemplates/datasets/speakers/xiang/frames/xiang/xiang_007329.jpg"   
    src_kp_path: "/mllab/codehub/SpeechDrivesTemplates/datasets/speakers/xiang/tmp/cleaned_pose_2d/xiang/xiang_007329.npy"